---
title: "Applications of MINMI and GBRM"
author: "Victor Tsang (z5209633)"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load functions

```{r}
library(tidyverse)
library(readxl)

source("../src/garthwaite-robbins-munro-functions.R")
source("../src/minmi-functions.R")
source("../src/GRIWM.R")
source("../src/simulated-inversion.R")

theme_set(theme_bw())

alpha = 0.05
```

## Import Data

```{r}
cave_bear = read_excel(path='../data/fossildata.xlsx',
                     sheet="Ursus.spe.Eur.ext", 
                     range="M3:N33", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

mammoth = read_excel(path='../data/fossildata.xlsx',
                     sheet="Mammoths Eurasian", 
                     range="M3:N205", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

megaloceros = read_excel(path='../data/fossildata.xlsx',
                     sheet="Megaloceros", 
                     range="M3:N48", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

neanderthal = read_excel(path='../data/fossildata.xlsx',
                     sheet="NeandertalEur", 
                     range="M3:N147", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

bison = read_excel(path='../data/fossildata.xlsx',
                     sheet="BisPriscus.ext", 
                     range="M3:N15", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

jelephant = read_excel(path='../data/fossildata.xlsx',
                     sheet="Paleolox.Japan", 
                     range="M3:N13", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

cave_hyena = read_excel(path='../data/fossildata.xlsx',
                     sheet="CrocCroc.Eur", 
                     range="M3:N81", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

tmp = rbind(data.frame(age=cave_bear$age, sd=cave_bear$sd, dataset="Cave Bear"),
            data.frame(age=bison$age, sd=bison$sd, dataset="Steppe Bison"),
            data.frame(age=mammoth$age, sd=mammoth$sd, dataset="Eurasian Mammoth"),
            data.frame(age=cave_hyena$age, sd=cave_hyena$sd, dataset="Cave Hyena"))
```

## Histograms

```{r fig.height=3, fig.width=12}
p = tmp %>% ggplot(aes(x=age)) +
  geom_histogram(position="identity", color="black", fill="grey", bins=7) +
  facet_wrap(dataset ~ ., scale="free", nrow=1)

p
ggsave(file="../figures/applications-hists.svg", plot=p, width=12, height=3)
```

```{r}
K_df = tmp %>%
  group_by(dataset) %>%
  summarise(max(age), mean(sd), thetas=paste0("[", round(min(age) - 2*sd(age)), ", ", round(min(age) + sd(age)), "]"))

print(knitr::kable(K_df))
```

```{r}
library(knitr)
library(kableExtra)

K_df %>%
  kable(booktabs=T, col.names = c("Dataset", "$K$", "$\\sigma$", "$\\bm{\\theta}$"), format="latex", escape=F) %>%
  writeLines("../figures/table-applications-Ks.tex")
```


## Driver Function

```{r}

estimate_extinction = function (data, alpha = 0.05, label) {
  print(label)
  K = max(data$age)
  data = data[data$age < K,]
  
  dates = data$age
  sd = data$sd
  
  # SI-UGM
  theta.test_vec = seq(from = round(min(dates) - 2*sd(dates)),
                       to = round(min(dates) + sd(dates)))
  
  SIUGM.results = simulated_inversion(
    alpha = alpha,
    dates = dates,
    sd = sd,
    K = K,
    theta.test_vec = theta.test_vec,
    return_model = T
  )
  SIUGM = list(
    lower = SIUGM.results$lower,
    point = SIUGM.results$point,
    upper = SIUGM.results$upper,
    method = "SI-UGM"
  )

  # GRIWM - uncorrected
  griwm.uncorrected = GRIWM(
    df = data.frame(dates = dates, sd = sd),
    alpha = 0.05,
    K = K,
    p_t = 0.05,
    .n_iter = 10000,
    bias_adjusted = F
  )
  griwm.uncorrected.results = list(
    lower = griwm.uncorrected$lower_ci,
    point = griwm.uncorrected$centroid,
    upper = griwm.uncorrected$upper_ci,
    method = "GRIWM (q=0.05)"
  )

  # GRIWM - corrected
  griwm.corrected = GRIWM(
    df = data.frame(dates = dates, sd = sd),
    alpha = 0.05,
    K = K,
    p_t = 0.5,
    .n_iter = 10000,
    bias_adjusted = T
  )
  griwm.corrected.results = list(
    lower = griwm.corrected$lower_ci,
    point = griwm.corrected$centroid,
    upper = griwm.corrected$upper_ci,
    method = "GRIWM (q=0.5, bias adjusted)"
  )


  # MINMI
  MINMI.results = estimate_extinction.minmi(
    W = dates,
    sd = sd,
    level = 1 - alpha,
    K = K,
    return_Bs=T
  )
  MINMI = list(
    lower = MINMI.results$lower,
    point = MINMI.results$point,
    upper = MINMI.results$upper,
    method = "MINMI"
  )
  print(MINMI.results)

  # SIRM
  SIRM = estimate_CI.rm(
    W = dates,
    K = K,
    alpha = alpha,
    max_iter = 3000,
    eps.mean = 0,
    eps.sigma = mean(sd),
    .model = SIUGM.results$model,
    .CI_estimates = list(lower = SIUGM.results$lower, upper = SIUGM.results$upper)
  )
  SIRM$method = "SI-RM"
  
  # Collate and return results
  estimates = data.frame(
    method = factor(),
    lower = numeric(),
    upper = numeric(),
    point = numeric(),
    n = numeric(),
    sigma = numeric(),
    dataset = factor()
  )
  estimates = rbind(estimates, MINMI, SIUGM, SIRM, griwm.uncorrected.results, griwm.corrected.results)
  estimates$n = length(dates)
  estimates$sigma = mean(sd)
  estimates$dataset = paste0(label, " (n=", length(dates), ")")
  return(estimates)
} 
```




## Estimations

```{r}

cave_bear.estimates = estimate_extinction(data = cave_bear, label = "Cave Bear")

mammoth.estimates = estimate_extinction(data = mammoth, label = "Eurasian Mammoth")

# megaloceros.estimates = estimate_extinction(data = megaloceros, label="Giant Deer")


# neanderthal.estimates = estimate_extinction(data = neanderthal, label="Neanderthal")


bison.estimates = estimate_extinction(data=bison, label="Steppe Bison")


# jelephant.estimates = estimate_extinction(data=jelephant, label="Japanese Elephant")


cave_hyena.estimates = estimate_extinction(data=cave_hyena, label="Cave Hyena")

all_results = rbind(cave_bear.estimates, mammoth.estimates, bison.estimates, cave_hyena.estimates)
```


## Combined


```{r fig.height=5, fig.width=8}
p = all_results %>%
  mutate(method_cat = ifelse(method == "MINMI", 2, ifelse(method == "SI-RM", 1, 0))) %>%
  # pivot_longer(cols = c(lower, upper),
  #              names_to = "endpoints") %>%
  ggplot(aes(colour=method)) +
  # geom_line(aes(y=reorder(method, method_cat), x=value)) +
  geom_pointrange(aes(y=reorder(method, method_cat), xmin=lower, xmax=upper, x=point)) +
  guides(colour="none") +
  labs(x="Years (BP)", y=NULL) +
  facet_wrap(fct_reorder(dataset, n) ~ ., ncol=2, dir='v', scale="free_x")
p
```

```{r}
ggsave(file="../figures/applications.svg", plot=p, height=5, width=8)
```


```{r}
library(knitr)

all_results %>%
  mutate(Extinction = paste0(scales::label_comma()(round(point, 1)), " (", scales::label_comma()(round(lower, 1)), " - ", scales::label_comma()(round(upper, 1)), ")"),
         Method = method) %>%
  select(Method, dataset, Extinction) %>%
  pivot_wider(names_from=dataset, values_from=Extinction) %>%
  kable(booktabs=T, format="latex") %>%
  writeLines("../figures/table-applications-CIs.tex")
```


```{r}
tmp %>% group_by(dataset) %>% summarise(min(age))
```


## Case Study: Cave Bear

```{r}
case_study = cave_bear.estimates %>%
  filter(method %in% c("MINMI", "SI-RM")) %>%
  select(method, lower, upper) %>%
  add_row(method = "GRIWM",
          lower = 24291,
          upper = 26081) %>%
  add_row(method = "GRIWM (conservative)",
          lower = 26117,
          upper = 27007) %>%
  pivot_longer(cols = c(lower, upper),
               names_to = "endpoints")

case_study
```


```{r fig.height=3, fig.width=7}
cave_bear.conf_int.plot = case_study %>%
  ggplot() +
  geom_line(aes(y=reorder(method, value), x=value, colour=method)) +
  # geom_point(data = data.frame(age = rep(cave_bear$age, length(case_study$method)),
  #                              method = rep(case_study$method, length(cave_bear$age))),
  #            aes(x = age, y = method),
  #            alpha=0.4,
  #            shape = 4) +
  guides(colour = "none") +
  labs(y = NULL, x = NULL, title = "Cave Bear Confidence Intervals")
cave_bear.conf_int.plot
```

```{r}
ggsave(plot=cave_bear.conf_int.plot,
       filename = "../figures/plot-application-cave-bear.svg",
       dpi=320,
       height=3,
       width=7)
```

```{r}
case_study_tbl = case_study %>%
  pivot_wider(id_cols=method, names_from = endpoints) %>%
  mutate(across(where(is.numeric), round, 1)) %>%
  mutate(width = upper - lower,
         interval = paste(lower, "---", upper)) %>%
  select(method, interval, width) %>%
  rename(Method = method,
         `95% CI` = interval,
         Width = width)
case_study_tbl
```

```{r}
case_study_tbl %>%
  kable(booktabs=T, format="latex") %>%
  writeLines("../figures/table-case-study-results.tex")
```

=======
---
title: "Applications of MINMI and GBRM"
author: "Victor Tsang (z5209633)"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load functions

```{r}
library(tidyverse)
library(readxl)

source("../src/garthwaite-robbins-munro-functions.R")
source("../src/minmi-functions.R")
source("../src/GRIWM.R")
source("../src/simulated-inversion.R")

theme_set(theme_bw())

alpha = 0.05
```

## Import Data

```{r}
cave_bear = read_excel(path='../data/fossildata.xlsx',
                     sheet="Ursus.spe.Eur.ext", 
                     range="M3:N33", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

mammoth = read_excel(path='../data/fossildata.xlsx',
                     sheet="Mammoths Eurasian", 
                     range="M3:N205", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

megaloceros = read_excel(path='../data/fossildata.xlsx',
                     sheet="Megaloceros", 
                     range="M3:N48", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

neanderthal = read_excel(path='../data/fossildata.xlsx',
                     sheet="NeandertalEur", 
                     range="M3:N147", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

bison = read_excel(path='../data/fossildata.xlsx',
                     sheet="BisPriscus.ext", 
                     range="M3:N15", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

jelephant = read_excel(path='../data/fossildata.xlsx',
                     sheet="Paleolox.Japan", 
                     range="M3:N13", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

cave_hyena = read_excel(path='../data/fossildata.xlsx',
                     sheet="CrocCroc.Eur", 
                     range="M3:N81", 
                     col_names=c("age", "sd"), 
                     col_types=c('numeric', 'numeric'))

tmp = rbind(data.frame(age=cave_bear$age, sd=cave_bear$sd, dataset="Cave Bear"),
            data.frame(age=bison$age, sd=bison$sd, dataset="Steppe Bison"),
            data.frame(age=mammoth$age, sd=mammoth$sd, dataset="Eurasian Mammoth"),
            data.frame(age=cave_hyena$age, sd=cave_hyena$sd, dataset="Cave Hyena"))
```

## Histograms

```{r fig.height=3, fig.width=12}
p = tmp %>% ggplot(aes(x=age)) +
  geom_histogram(position="identity", color="black", fill="grey", bins=7) +
  facet_wrap(dataset ~ ., scale="free", nrow=1)

p
ggsave(file="../figures/applications-hists.svg", plot=p, width=12, height=3)
```

```{r}
K_df = tmp %>%
  group_by(dataset) %>%
  summarise(max(age), mean(sd), thetas=paste0("[", round(min(age) - 2*sd(age)), ", ", round(min(age) + sd(age)), "]"))

print(knitr::kable(K_df))
```

```{r}
library(knitr)
library(kableExtra)

K_df %>%
  kable(booktabs=T, col.names = c("Dataset", "$K$", "$\\sigma$", "$\\bm{\\theta}$"), format="latex", escape=F) %>%
  writeLines("../figures/table-applications-Ks.tex")
```


## Driver Function

```{r}

estimate_extinction = function (data, alpha = 0.05, label) {
  print(label)
  K = max(data$age)
  data = data[data$age < K,]
  
  dates = data$age
  sd = data$sd
  
  # SI-UGM
  theta.test_vec = seq(from = round(min(dates) - 2*sd(dates)),
                       to = round(min(dates) + sd(dates)))
  
  SIUGM.results = simulated_inversion(
    alpha = alpha,
    dates = dates,
    sd = sd,
    K = K,
    theta.test_vec = theta.test_vec,
    return_model = T
  )
  SIUGM = list(
    lower = SIUGM.results$lower,
    point = SIUGM.results$point,
    upper = SIUGM.results$upper,
    method = "SI-UGM"
  )

  # GRIWM - uncorrected
  griwm.uncorrected = GRIWM(
    df = data.frame(dates = dates, sd = sd),
    alpha = 0.05,
    K = K,
    p_t = 0.05,
    .n_iter = 10000,
    bias_adjusted = F
  )
  griwm.uncorrected.results = list(
    lower = griwm.uncorrected$lower_ci,
    point = griwm.uncorrected$centroid,
    upper = griwm.uncorrected$upper_ci,
    method = "GRIWM (q=0.05)"
  )

  # GRIWM - corrected
  griwm.corrected = GRIWM(
    df = data.frame(dates = dates, sd = sd),
    alpha = 0.05,
    K = K,
    p_t = 0.5,
    .n_iter = 10000,
    bias_adjusted = T
  )
  griwm.corrected.results = list(
    lower = griwm.corrected$lower_ci,
    point = griwm.corrected$centroid,
    upper = griwm.corrected$upper_ci,
    method = "GRIWM (q=0.5, bias adjusted)"
  )


  # MINMI
  MINMI.results = estimate_extinction.minmi(
    W = dates,
    sd = sd,
    level = 1 - alpha,
    K = K,
    return_Bs=T
  )
  MINMI = list(
    lower = MINMI.results$lower,
    point = MINMI.results$point,
    upper = MINMI.results$upper,
    method = "MINMI"
  )
  print(MINMI.results)

  # SIRM
  SIRM = estimate_CI.rm(
    W = dates,
    K = K,
    alpha = alpha,
    max_iter = 3000,
    eps.mean = 0,
    eps.sigma = mean(sd),
    .model = SIUGM.results$model,
    .CI_estimates = list(lower = SIUGM.results$lower, upper = SIUGM.results$upper)
  )
  SIRM$method = "SI-RM"
  
  # Collate and return results
  estimates = data.frame(
    method = factor(),
    lower = numeric(),
    upper = numeric(),
    point = numeric(),
    n = numeric(),
    sigma = numeric(),
    dataset = factor()
  )
  estimates = rbind(estimates, MINMI, SIUGM, SIRM, griwm.uncorrected.results, griwm.corrected.results)
  estimates$n = length(dates)
  estimates$sigma = mean(sd)
  estimates$dataset = paste0(label, " (n=", length(dates), ")")
  return(estimates)
} 
```




## Estimations

```{r}

cave_bear.estimates = estimate_extinction(data = cave_bear, label = "Cave Bear")

mammoth.estimates = estimate_extinction(data = mammoth, label = "Eurasian Mammoth")

# megaloceros.estimates = estimate_extinction(data = megaloceros, label="Giant Deer")


# neanderthal.estimates = estimate_extinction(data = neanderthal, label="Neanderthal")


bison.estimates = estimate_extinction(data=bison, label="Steppe Bison")


# jelephant.estimates = estimate_extinction(data=jelephant, label="Japanese Elephant")


cave_hyena.estimates = estimate_extinction(data=cave_hyena, label="Cave Hyena")

all_results = rbind(cave_bear.estimates, mammoth.estimates, bison.estimates, cave_hyena.estimates)
```


## Combined


```{r fig.height=5, fig.width=8}
p = all_results %>%
  mutate(method_cat = ifelse(method == "MINMI", 2, ifelse(method == "SI-RM", 1, 0))) %>%
  pivot_longer(cols = c(lower, upper),
               names_to = "endpoints") %>%
  ggplot(aes(colour=method)) +
  geom_line(aes(y=reorder(method, method_cat), x=value)) +
  # geom_pointrange(aes(y=reorder(method, method_cat), xmin=lower, xmax=upper, x=point)) +
  guides(colour="none") +
  labs(x="Years (BP)", y=NULL) +
  facet_wrap(fct_reorder(dataset, n) ~ ., ncol=2, dir='v', scale="free_x")
p
```

```{r}
ggsave(file="../figures/applications.svg", plot=p, height=5, width=8)
```


```{r}
library(knitr)

all_results %>%
  mutate(Extinction = paste0(scales::label_comma()(round(point, 1)), " (", scales::label_comma()(round(lower, 1)), " - ", scales::label_comma()(round(upper, 1)), ")"),
         Method = method) %>%
  select(Method, dataset, Extinction) %>%
  pivot_wider(names_from=dataset, values_from=Extinction) %>%
  kable(booktabs=T, format="latex") %>%
  writeLines("../figures/table-applications-CIs.tex")
```


```{r}
tmp %>% group_by(dataset) %>% summarise(min(age))
```


## Case Study: Cave Bear

```{r}
case_study = cave_bear.estimates %>%
  filter(method %in% c("MINMI", "SI-RM")) %>%
  select(method, lower, upper) %>%
  add_row(method = "GRIWM",
          lower = 24291,
          upper = 26081) %>%
  add_row(method = "GRIWM (conservative)",
          lower = 26117,
          upper = 27007) %>%
  pivot_longer(cols = c(lower, upper),
               names_to = "endpoints")

case_study
```


```{r fig.height=3, fig.width=7}
cave_bear.conf_int.plot = case_study %>%
  ggplot() +
  geom_line(aes(y=reorder(method, value), x=value, colour=method)) +
  # geom_point(data = data.frame(age = rep(cave_bear$age, length(case_study$method)),
  #                              method = rep(case_study$method, length(cave_bear$age))),
  #            aes(x = age, y = method),
  #            alpha=0.4,
  #            shape = 4) +
  guides(colour = "none") +
  labs(y = NULL, x = NULL, title = "Cave Bear Confidence Intervals")
cave_bear.conf_int.plot
```

```{r}
ggsave(plot=cave_bear.conf_int.plot,
       filename = "../figures/plot-application-cave-bear.svg",
       dpi=320,
       height=3,
       width=7)
```
