---
title: "Monte Carlo Estimation Simulation Tests"
author: "Victor Tsang"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    highlight: pygments
    toc: true
    toc_float: true
    toc_collapsed: false
    toc_smooth_scroll: false
    toc_depth: 5
header_includes:
  - \newcommand{\Var}{\mathrm{Var}}
  - \newcommand{\E}{\mathbb{E}}
---

```{=html}
<style>
body
  { counter-reset: source-line 0; }
pre.numberSource code
  { counter-reset: none; }
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  attr.source='.numberLines',
  class.source = "numberLines lineAnchors",
  root.dir='C:/Users/victo/Documents/c-git-repos/HonoursThesis2022',
  error=TRUE
)
```

```{r}
library(readxl)
library(tidyverse)
library(latex2exp)
source("../src/minmi-functions.R")
```



```{r}
# Import mammoth data from fossildata.xlsx
fossil_dataframe = read_excel(
  path='../data/fossildata.xlsx', 
  sheet="MammothPrimEBer", 
  range="M3:N36", 
  col_names=c("age", "sd"), 
  col_types=c('numeric', 'numeric')
)
```

## Check $P_\theta (X + \varepsilon > m)$ is stochastically increasing in $\theta$

```{r}

K = 18000
theta.range = seq(10000, 17500, by=50)
nThetas = length(theta.range)

B=500
n=30

eps.mean = 0
fossil_dataframe = fossil_dataframe[fossil_dataframe$age<K,]
eps.sigma = mean(fossil_dataframe$sd)

P = A1 = A2 = phi.hat = equation1 = rep(NA, nThetas)

set.seed(2022)

u = matrix(runif(1*B, 0, 1), ncol=B)

theta.true = 12000

m = theta.true+10 ##min(fossil_dataframe$age)

q = 0.025

for (i in 1:nThetas) {
  P[i] = estimating_eqn(theta = theta.range[i], q=q, K = K, u=u, m=m, n=n, eps.mean = eps.mean, eps.sigma = eps.sigma) +q^(1/n)
}

res.df = data.frame(theta=theta.range,
                    A1 = A1,
                    A2 = A2,
                    phi.hat = phi.hat,
                    P = P)
head(res.df)
```

```{r}
res.df %>%
  group_by() %>%
  summarise(min(A1), max(A1), min(A2), max(A2), min(phi.hat), max(phi.hat))
```

```{r}
p = res.df %>%
  ggplot(aes(x=theta, y=P)) +
  geom_line() +
  labs(title=TeX("$P_\\theta (X + \\epsilon > m)$ for increasing \\theta"),
       x=TeX("\\theta"),
       y=TeX("P")) +
  theme_bw()

p
ggsave(plot=p, filename="../figures/minmi-stochastically-increasing.png", width=6, height=4)
```

```{r}
res.df %>%
  mutate(Pn = P**n) %>% 
  ggplot(aes(x=theta, y=Pn)) +
  geom_line() +
  labs(title=TeX("$P_\\theta (X + \\epsilon > m)^n$ for increasing theta"),
       x=TeX("\\theta"),
       y=TeX("P^n"))
```


```{r}
res.df %>%
  select(theta, A1) %>%
  ggplot(aes(x=theta, y=A1)) +
  geom_line() +
  labs(title=TeX("A1 for increasing \\theta"),
       x=TeX("\\theta"))
```

```{r}
res.df %>%
  select(theta, A2) %>%
  ggplot(aes(x=theta, y=A2)) +
  geom_line() +
  labs(title=TeX("A2 for increasing \\theta"),
       x=TeX("\\theta"))
```

```{r}
res.df %>%
  select(theta, phi.hat) %>%
  ggplot(aes(x=theta, y=phi.hat)) +
  geom_line() +
  labs(title=TeX("\\widehat{\\phi(\\theta)} for increasing \\theta"),
       x=TeX("\\theta"),
       y=TeX("\\widehat{\\phi(\\theta)}"))
```

```{r}

```




## Plot the function that we want to solve to determine a suitable search interval.

```{r}
theta = 12500
n.trials = 100
theta.roots = seq(from=10000, to=15000, length.out=50)

n.theta.roots = length(theta.roots)
m = rep(NA, n.trials)
x = rep(theta.roots, n.trials)
trial = rep(1:n.trials, each=n.theta.roots)

target_f.lower_q = rep(NA, n.trials * n.theta.roots)
target_f.upper_q = rep(NA, n.trials * n.theta.roots)
target_f.lower_q.vals = rep(NA, n.theta.roots)
target_f.upper_q.vals = rep(NA, n.theta.roots)

for (i in 1:n.trials) {
  m[i] = min(simulateFossils(n, theta, K, eps.mean, eps.sigma)$W)
  start_idx = (i-1) * n.theta.roots + 1
  end_idx = i * n.theta.roots
  target_f.lower_q.vals = sapply(
    X=theta.roots,
    FUN=solve.for.theta_q.hat,
    K = K,
    n = n,
    u = u,
    q = 0.025,
    m = m[i],
    eps.mean = eps.mean,
    eps.sigma = eps.sigma
  )
  target_f.upper_q.vals = sapply(
    X=theta.roots,
    FUN=solve.for.theta_q.hat,
    K = K,
    n = n,
    u = u,
    q = 0.975,
    m = m[i],
    eps.mean = eps.mean,
    eps.sigma = eps.sigma
  )
  target_f.lower_q[ start_idx: end_idx] = target_f.lower_q.vals
  target_f.upper_q[ start_idx: end_idx] = target_f.upper_q.vals
}

target.trials.df = data.frame(
  x=x,
  trial=trial,
  m=rep(m, each=n.theta.roots),
  q_lower=target_f.lower_q,
  q_upper=target_f.upper_q
)

colours = c("q_lower" = '#F8766D', "q_upper"='#619CFF')

ggplot(target.trials.df) +
  geom_line(aes(x=x, y=q_lower, group=trial, colour="q_lower")) +
  geom_line(aes(x=x, y=q_upper, group=trial, colour="q_upper")) +
  geom_hline(yintercept=0, lty=1, alpha=0.4) +
  # geom_vline(xintercept=c(theta, K), lty=2) +
  ggtitle("Equation (1) values for different thetas") +
  labs(x = "Theta",
       y = "Equation Value",
       color = "Legend") +
  scale_color_manual(values = colours)
```

```{r}
target.trials.df %>%
  summarise(min(q_lower), max(q_lower), min(q_upper), max(q_upper))
```

```{r}
target.trials.df %>%
  filter(abs(q_upper) < 1e-3)
```


## Prove P(M > m) is stochastically increasing

$$
\phi(\theta) = \int^{m-\theta}_{-\infty} \frac{K-m}{K - e - \theta} f_\varepsilon(e) de

\\

P(M \ge m) = \prod_{i=1}^n P(W \ge m) =\prod_{i=1}^n 1 - \frac{F_\varepsilon (m-\theta)}{F_\varepsilon (K-\theta)} + \frac{\phi(\theta)}{F_\varepsilon (K-\theta)}
$$

$$

\begin{aligned}
\frac{\partial}{\partial \theta} P
  &= \frac{\partial}{\partial \theta} \left[ 1 - \frac{F_\varepsilon (m-\theta)}{F_\varepsilon (K-\theta)} + \frac{\phi(\theta)}{F_\varepsilon (K-\theta)} \right] \\
  &= \frac{\partial}{\partial \theta} \left[ 1 + \frac{\phi(\theta) - F_\varepsilon (m-\theta)}{F_\varepsilon (K-\theta)} \right] \\
  &= \frac{ F_\varepsilon(K-\theta){ \frac{\partial}{\partial \theta} \Big[\phi(\theta) - F_\varepsilon (m-\theta) \Big]} - { \Big[\phi(\theta) - F_\varepsilon (m-\theta) \Big] \frac{\partial}{\partial \theta}F_\varepsilon(K-\theta) } }{ \left[ F_\varepsilon (K-\theta) \right]^2 } \\
  &= \frac{ \overbrace{ F_\varepsilon(K-\theta){ \Big[ \frac{\partial}{\partial \theta} \phi(\theta) - f_\varepsilon (m-\theta) \Big] } }^{A} + \overbrace{ (-1)\Big[ \phi(\theta) - F_\varepsilon (m-\theta) \Big] f_\varepsilon(K-\theta) }^{B} }{ \left[ F_\varepsilon (K-\theta) \right]^2 }
\end{aligned}
$$

$$
\phi(\theta) = \int^{m-\theta}_{-\infty} \frac{K-m}{K - e - \theta} f_\varepsilon(e) de \le \int^{m-\theta}_{-\infty} f_\varepsilon(e) de = F_\varepsilon(m-\theta) \\
(\text{because } -\infty < e < m - \theta \implies 0 < \frac{K-m}{K-e-\theta} < 1) \\
\therefore B \ge 0
$$

$$
\begin{aligned}
\frac{\partial}{\partial \theta} \phi(\theta) = \frac{\partial}{\partial \theta}  \int^{m-\theta}_{-\infty} \frac{K-m}{K - e - \theta} f_\varepsilon(e) de \\
\end{aligned}
$$

$$

$$


$$
\hat\phi (\theta) = \sum_{b=1}^B \frac{K-m}{K-e_{ib}-\theta}, \quad e_{ib} \le m-\theta
$$



$$
\begin{aligned}
(1) &\quad F_\varepsilon(m-\theta) = \int^{m-\theta}_{-\infty} f_\varepsilon (e) de\\
(2) &\quad \frac{\partial}{\partial \theta} F_\varepsilon(m - \theta) = f_\varepsilon(m - \theta) \times (-1)\\
\end{aligned}
$$

$$
\frac{dF}{d\theta} = \frac{dF}{d(m-\theta)} \frac{d(m-\theta)}{d\theta}
$$









