---
title: "Estimating Monte Carlo Confidence Intervals for Fossil Data using Garthwaite 1992"
author: "Victor Tsang"
date: "08/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Assumptions

-   Uniform Fossil Recovery: fossil ages are uniformly distributed
-   Normally distributed measurement error
-   Have an initial point estimate (observed minimum)

### Import data

```{r}
library(readxl)
# Import mammoth data from fossildata.xlsx
fossil_dataframe = read_excel(
  path='../data/fossildata.xlsx', 
  sheet="MammothPrimEBer", 
  range="M3:N36", 
  col_names=c("age", "sd"), 
  col_types=c('numeric', 'numeric')
)
```

```{r}
load("../data/synthetic-data.RData")
dates = datasets[datasets$error_factor == 1, ][1, ]$W[[1]]
n = length(dates)
theta.hat.y = min(dates)

set.seed(22)
alpha = 0.05
K = 20000 # upper bound for dates we can get fossils in

fossil_dataframe = fossil_dataframe[fossil_dataframe$age<K,]
dating_error.sd = mean(fossil_dataframe$sd)
```

### Perform Simulated Inversion

```{r}
library(mgcv)
theta.test_vec = seq(5000, 14000)
n.theta.test_vec = length(theta.test_vec)

# Calculate S_star
S_star = rep(NA, n.theta.test_vec)
for (i in 1:n.theta.test_vec) {
  fossil.resamples = runif(n, theta.test_vec[i], K) + rnorm(n, 0, dating_error.sd)
  S_star[i] = min(fossil.resamples)
}

# Create indicators
m = min(dates)
indicator_vec = sapply(S_star, function(x) ifelse(x > m, 1, 0))

# Estimate model using smooth regression
model_gam = gam(indicator_vec ~ s(theta.test_vec),
                data=data.frame(theta.test_vec, indicator_vec),
                family=binomial)

# Use inversion
get_min_est <- function (theta.test_vec , model_gam, q){
  prediction <- function (theta.test_vec , model_gam ){
    yval <- predict ( model_gam , newdata = data.frame ( theta.test_vec = theta.test_vec ), type = "response")
    return ( yval - q )
  }
  theta_est <- uniroot ( prediction , lower = 5000 , upper = 15000, extendInt = "yes", model_gam = model_gam, maxiter = 2000)$root
  return ( theta_est )
}

lower = get_min_est(theta.test_vec, model_gam, q=alpha/2)
upper = get_min_est(theta.test_vec, model_gam, q=1-alpha/2)
point = get_min_est(theta.test_vec, model_gam, q=0.5)
c(lower, point, upper)
```

### Run RM process

```{r}
source("../src/garthwaite-robbins-munro-functions.R")

results.si_rm = estimate_CI.rm(W=dates,
                               K=K,
                               alpha=0.05,
                               max_iter=10000,
                               eps.mean=0,
                               eps.sigma=dating_error.sd,
                               .model=model_gam,
                               .CI_estimates = list(lower=lower, upper=upper),
                               return_iters=T)

names(results.si_rm)
```

```{r}
c(results.si_rm$lower, results.si_rm$point, results.si_rm$upper)
```


```{r}
plot(results.si_rm$lower.iters, type="b", col="red", ylim=c(min(results.si_rm$lower.iters, results.si_rm$upper.iters), max(results.si_rm$lower.iters, results.si_rm$upper.iters)))
lines(results.si_rm$upper.iters, type="b", col="blue")
abline(h=10000, lty=2)
```

