---
title: "Simulation Experiment Results"
author: "Victor Tsang (z5209633)"
date: "`r Sys.Date()`"
output:
  pdf_document:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load in the results

```{r, warning=FALSE, message=FALSE}
library(knitr)
library(tidyverse)

library(gridExtra)
library(latex2exp)

load("../data/synthetic-data.RData")
attach(synthetic.data.config)
```

### Cleaning up and renaming things

```{r}
estimates = readRDS("../data/sim_exp-estimate_extinction_results.RDS")
```

```{r}
estimates = estimates %>%
  mutate(
    method_cat = ifelse(
      method %in% c("SI-RM", "MINMI", "SI-UGM"),
      "Proposed Methods",
      "Existing Methods"
    ),
    method = ifelse(
      method == "GRIWM",
      "GRIWM (q=0.05)",
      ifelse(
        method == "GRIWM-corrected",
        "GRIWM-BA (q=0.5)",
        ifelse(method == "STRAUSS",
               "Strauss",
               ifelse(method == "SI-UGM",
                      "Simulated Inversion (Huang)",
                      method))
      )
    )
  )

estimates %>%
  group_by(error_factor, method) %>%
  summarise(n(), .groups='drop') %>%
  pivot_wider(id_cols = method, names_from = error_factor, values_from = `n()`)
```

## MSE Standard Errors

```{r}
estimates %>%
  select(error_factor, method, point) %>%
  mutate(sq_err= (point - theta.true)^2) %>%
  group_by(error_factor, method) %>%
  summarise(SE_SD_000 = sd(sq_err)/sqrt(1000) /1000, .groups='drop') %>%
  mutate(error_factor = paste0(error_factor, "*sigma")) %>%
  pivot_wider(id_cols=method,
              names_from=error_factor,
              values_from=SE_SD_000) %>%
  mutate(across(where(is.numeric), function(x) paste0(round(x, 1), "k")))
```

#### Compute Metrics

```{r}
# Point estimates
performance.point_estimates = estimates %>%
  filter(!is.na(point)) %>%
  group_by(error_factor, method, method_cat) %>%
  summarise(MSE_000 = mean((point - theta.true)^2)/1000,
            bias = mean(point)-theta.true,
            variance_000 = var(point)/1000,
            avg_runtime = round(mean(point_runtime), 5))
kable(performance.point_estimates)

# Confidence Intervals
performance.conf_int_estimates = estimates %>%
  filter(!is.na(conf_int_runtime)) %>%
  mutate(width = upper - lower,
         contains_theta = ifelse(theta.true > lower & theta.true < upper, 1, 0)) %>%
  group_by(error_factor, method, method_cat) %>%
  summarise(Coverage = round(mean(contains_theta) * 100, 1),
            `Average Width` = round(mean(width), 2),
            `Average Runtime` = round(mean(conf_int_runtime), 5)) %>%
  ungroup() %>%
  arrange(desc(Coverage), `Average Width`, `Average Runtime`)
kable(performance.conf_int_estimates)
```

### Point Estimates

```{r}
performance.point_estimates.long = performance.point_estimates %>%
  rename(Error = error_factor,
         Method = method,
         Category = method_cat,
         MSE = MSE_000,
         Bias = bias,
         Variance = variance_000,
         Runtime = avg_runtime) %>%
  pivot_longer(cols=c(MSE, Bias, Variance, Runtime),
               names_to = "Metric") %>%
  mutate(Method = factor(Method),
         Category = factor(Category),
         Metric = factor(Metric))

head(performance.point_estimates.long)
```

#### Tables

```{r results='asis'}
library(kableExtra)
for (err in error_factors) {
  experiment.results = performance.point_estimates %>%
    filter(error_factor == err) %>%
    ungroup() %>%
    mutate(across(!c(method, avg_runtime, method_cat), round)) %>%
    mutate(avg_runtime = round(avg_runtime, digits = 5)) %>%
    arrange(MSE_000) %>%
    select(-c(error_factor, method_cat))
  
  print(kable(experiment.results))
  
  experiment.results.kbl = experiment.results %>%
    kable(
      booktabs = T,
      col.names = c("", "(000's years)", "(years)", "(000's years)", "(seconds)"),
      format = "latex"
    ) %>%
    add_header_above(
      c(
        "Method" = 1,
        "MSE" = 1,
        "Bias" = 1,
        "Variance" = 1,
        "Average Runtime" = 1
      ),
      line = F,
      align = c("l", "c", "c", "c", "c")
    )
  
  writeLines(
    experiment.results.kbl,
    paste0("../figures/table-sim-exp-point-error", err, ".tex")
  )
}
```

#### All charts

```{r fig.width=15}
metrics = unique(performance.point_estimates.long$Metric)
performance.point_estimates.plots = lapply(metrics, function(met) {
  p = ggplot(data = filter(performance.point_estimates.long, Metric == met & Category == "Existing Methods"),
             aes(x = Error, y = value, group = Method, colour = "Existing Methods")) +
    geom_line() +
    geom_point() +
    geom_point(
      data=filter(performance.point_estimates.long, Metric == met & Category == "Proposed Methods"),
      mapping=aes(x=Error, y=value, colour = reorder(Method, value, decreasing = T)),
      colour='darkgray') +
    geom_line(
      data=filter(performance.point_estimates.long, Metric == met & Category == "Proposed Methods"),
      mapping=aes(x=Error, y=value, group=Method, colour = reorder(Method, value, decreasing = T))) +
    theme_bw() +
    labs(title = paste(met, "by Error"), ylab=NULL, colour = "Method") +
    theme(rect = element_rect(fill = "transparent")) +
    scale_color_manual(values = c("SI-RM" = "#619CFF", "MINMI" = "#F8766D", "Existing Methods" = "darkgray"))
  if (met %in% c("MSE", "Runtime")) {
    p = p+scale_y_log10()
  }
  p
})

performance.point_estimates.plots[[1]] = performance.point_estimates.plots[[1]] + ylab("000's")
performance.point_estimates.plots[[2]] = performance.point_estimates.plots[[2]] + ylab("Years")
performance.point_estimates.plots[[3]] = performance.point_estimates.plots[[3]] + ylab("000's")
performance.point_estimates.plots[[4]] = performance.point_estimates.plots[[4]] + ylab("Seconds")

performance.point_estimates.plot.grid = do.call(grid.arrange, performance.point_estimates.plots)
performance.point_estimates.plot.grid
```



```{r}
ggsave(plot = performance.point_estimates.plot.grid,
       file = "../figures/plot-sim-exp-point-est-grid.png",
       dpi=320,
       width=12,
       bg = 'transparent')

for (i in 1:length(metrics)) {
  ggsave(plot = performance.point_estimates.plots[[i]],
         file = paste0("../figures/plot-sim-exp-point-est-", metrics[i], ".png"),
         dpi=320,
         width=8, height=5,
         bg = 'transparent')
}
```

#### Bias and Variance

```{r, fig.height=6, fig.width=12}
perf.point_estimates.bias_var.plot = performance.point_estimates.long %>%
  filter(Metric %in% c("Bias", "Variance")) %>%
  ggplot(aes(x=Error, y=value, colour=reorder(Method, value))) +
  geom_line(size=0.4) +
  geom_point() +
  # facet_grid(Metric ~ Category, scale="free_y") +
  facet_wrap(Metric ~., scale="free") +
  labs(colour = "Method", y=NULL) +
  theme_bw() +
  theme(text=element_text(size=15),
        strip.text.x = element_text(size = 15))

perf.point_estimates.bias_var.plot
```

```{r}
ggsave(plot = perf.point_estimates.bias_var.plot,
       file = "../figures/plot-sim-exp-point-est-Bias-Variance.svg",
       width=12, height=6,
       dpi = 320,
       bg = 'transparent')
```


### Confidence Intervals

```{r}
performance.conf_int_estimates.long = performance.conf_int_estimates %>%
  rename(Error = error_factor, Method = method, Category = method_cat, Width = `Average Width`, Runtime = `Average Runtime`) %>%
  pivot_longer(cols=c(Coverage, Width, Runtime),
               names_to = "Metric")
  
head(performance.conf_int_estimates.long)
```

#### Tables

```{r results='asis'}
options(scipen = 9)
for (metric in c("Coverage", "Average Width", "Average Runtime")) {
  experiment.results.conf_int = performance.conf_int_estimates %>%
    select(c(method, error_factor, one_of(metric))) %>%
    pivot_wider(
      id_cols = method,
      names_from = error_factor,
      values_from = one_of(metric),
      names_prefix = paste(metric, "| error = sigma*")
    ) %>%
    arrange(!!syms(paste(metric, "| error = sigma*0")))
  print(kable(experiment.results.conf_int))
  
  experiment.results.kbl = experiment.results.conf_int %>%
    kable(
      col.names = c("", paste0(c(0, 0.5, 1, 2), r"{*$\sigma$}")),
      booktabs = T,
      format = "latex",
      escape = FALSE
    ) %>%
    add_header_above(unlist(lst("Method" = 1,!!metric := 4)), line = F)
  writeLines(
    experiment.results.kbl,
    paste0(
      "../figures/table-sim-exp-conf-int-",
      str_replace(tolower(metric), " ", "-"),
      ".tex"
    )
  )
}
```

#### Densities

```{r fig.width=25, fig.height=4}
estimates %>%
  filter(!is.na(lower)) %>%
  select(method, lower, upper) %>%
  pivot_longer(cols=c(lower, upper)) %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x=value, fill=name)) +
  geom_density(alpha=0.25) +
  geom_vline(aes(xintercept=theta.true)) +
  facet_wrap(method ~ ., nrow=1) +
  theme_minimal() +
  labs(x=NULL, y=NULL)
```


#### Average CI (??? bit misleading)

```{r fig.width=8, fig.height=5}
p = estimates %>%
  filter(!is.na(lower) & error_factor == 1) %>%
  group_by(method_cat, method) %>%
  summarise(lower = mean(lower), upper=mean(upper), point=mean(point)) %>%
  mutate(width=upper-lower) %>%
  mutate(method_cat_int = ifelse(method_cat == "Existing Methods", 0, 1)) %>%
  ggplot(aes(colour=method_cat)) +
  geom_pointrange(aes(xmin=lower, xmax=upper, x=point, y=reorder(method, method_cat_int)), shape = 3) +
  guides(colour = guide_legend(reverse=TRUE)) +
  labs(y=NULL, x="Years (BP)",
       title="Simulation Experiment Confidence Intervals",
       colour="Method",
       subtitle="(Average of Interval Endpoints and Point Estimates)") +
  scale_x_continuous(breaks = seq(from=8000, to=11500, by=500)) +
  theme_bw()
p
```


```{r}
ggsave(filename="../figures/sim-exp-intervals.svg", plot=p, height=5, width=8,
       bg = 'transparent')
```

#### Coverage Probabilities

```{r fig.height=6, fig.width=10}
conf_int.coverage.plot = performance.conf_int_estimates.long %>%
  filter(Metric == "Coverage" & Category == "Proposed Methods") %>%
  ggplot(aes(x=Error, y=value, colour=reorder(Method, value, decreasing=T))) +
  geom_point() +
  geom_line(size=0.5) +
  geom_point(
    data=filter(performance.conf_int_estimates.long, Metric == "Coverage" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method),
    colour='darkgray') +
  geom_line(
    data=filter(performance.conf_int_estimates.long, Metric == "Coverage" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method, colour = "Existing Methods"),
    size = 0.5) +
  theme_bw() +
  labs(y = "Years", colour="Method", title="Coverage Probabilities") +
  scale_y_continuous(breaks=c(0, 25, 50, 75, 95, 100)) +
  theme(rect = element_rect(fill = "transparent")) +
  scale_color_manual(values = c("Simulated Inversion (Huang)" = "#F8766D", "SI-RM" = "#619CFF", "MINMI" = "#00BA38", "Existing Methods" = "darkgray"))

conf_int.coverage.plot
```

```{r}
ggsave(plot = conf_int.coverage.plot,
       filename = "../figures/plot-sim-exp-conf-coverage.png",
       dpi=320,
       height=6, width=10,
       bg = 'transparent')
```



#### Average Width

```{r fig.height=6, fig.width=10}
conf_int.widths.plot = performance.conf_int_estimates.long %>%
  filter(Metric == "Width" & Category == "Proposed Methods") %>%
  ggplot(aes(x=Error, y=value, colour=reorder(Method, value, decreasing=T))) +
  geom_point() +
  geom_line(size=0.5) +
  geom_point(
    data=filter(performance.conf_int_estimates.long, Metric == "Width" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method),
    colour='darkgray') +
  geom_line(
    data=filter(performance.conf_int_estimates.long, Metric == "Width" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method, colour = "Existing Methods"),
    size = 0.5) +
  # facet_grid(Metric ~ Category, scale="free_y") +
  theme_bw() +
  labs(y = "Years", colour="Method", title="Average Width of Estimated Confidence Intervals") +
  theme(rect = element_rect(fill = "transparent")) +
  scale_color_manual(values = c("Simulated Inversion (Huang)" = "#F8766D", "SI-RM" = "#619CFF", "MINMI" = "#00BA38", "Existing Methods" = "darkgray"))

conf_int.widths.plot
```

```{r fig.height=6, fig.width=10}
conf_int.runtime.plot = performance.conf_int_estimates.long %>%
  filter(Metric == "Runtime" & Category == "Proposed Methods") %>%
  ggplot(aes(x=Error, y=value, colour=reorder(Method, value, decreasing=T))) +
  geom_point() +
  geom_line(size=0.5) +
  geom_point(
    data=filter(performance.conf_int_estimates.long, Metric == "Runtime" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method),
    colour='darkgray') +
  geom_line(
    data=filter(performance.conf_int_estimates.long, Metric == "Runtime" & Category == "Existing Methods"),
    mapping=aes(x=Error, y=value, group=Method, colour = "Existing Methods"),
    size = 0.5) +
  theme_bw() +
  scale_y_continuous(trans=scales::log10_trans()) +
  labs(y = "Seconds", colour="Method", title="Average Runtime of Confidence Interval Estimation") +
  theme(rect = element_rect(fill = "transparent")) +
  scale_color_manual(values = c("Existing Methods" = "darkgray", "Simulated Inversion (Huang)" = "#F8766D", "SI-RM" = "#619CFF", "MINMI" = "#00BA38"))

conf_int.runtime.plot
```

```{r}
ggsave(plot = conf_int.widths.plot,
       filename = "../figures/plot-sim-exp-conf-widths.png",
       dpi=320,
       height=6, width=10,
       bg = 'transparent')

ggsave(plot = conf_int.runtime.plot,
       filename = "../figures/plot-sim-exp-conf-runtime.png",
       dpi=320,
       height=6, width=10,
       bg = 'transparent')
```


## Monte Carlo Samples for MINMI

```{r}
B.minmi = readRDS("../data/sim_exp-B-minmi.RDS")
B.minmi = B.minmi %>% arrange(error_factor) %>% mutate(error_factor = paste0(error_factor, r"{*$\sigma$}"))

B.minmi.kbl = B.minmi %>%
  filter(error_factor != 0) %>%
  kable(col.names = c("Variation", "$q = 0.025$", "$q = 0.5$", "$q = 0.975$"),
        booktabs=T, format="latex", escape = FALSE) %>%
  add_header_above(c(`Measurement Error`=1, `$B$`=3), line=F)

print(B.minmi.kbl)

writeLines(B.minmi.kbl, "../figures/table-sim-exp-minmi-Bs.tex")
```