---
title: "simulated inversion testing"
author: "Victor Tsang (z5209633)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
# Import mammoth data from fossildata.xlsx
fossil_dataframe = read_excel(
  path='../data/fossildata.xlsx', 
  sheet="MammothPrimEBer", 
  range="M3:N36", 
  col_names=c("age", "sd"), 
  col_types=c('numeric', 'numeric')
)
fossil_dataframe = fossil_dataframe[fossil_dataframe$age<K,]

load("../data/synthetic-data.RData")
attach(synthetic.data.config)

dates = datasets[1, ]$W[[1]]
m = min(dates)

standard_errors = fossil_dataframe$sd[1:n]
print(K)
print(theta.true)
```

```{r}
set.seed(seed)
source("simulated-inversion.R")
dates = datasets[325, ]$W[[1]]
simulated_inversion(alpha=0.05, dates=dates, sd=1*fossil.sd, K=K, theta.test_vec=seq(5000, 15000), dating_error.mean=0)
```

```{r}
simulated_inversion(alpha=0.05, dates=datasets[48, ]$W[[1]], sd=4*fossil.sd, K=K, theta.test_vec=seq(5000, 15000), dating_error.mean=0)
```

