---
title: "Estimating Monte Carlo Confidence Intervals for Fossil Data using Garthwaite 1992"
author: "Victor Tsang"
date: "08/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Assumptions

* Uniform Fossil Recovery: fossil ages are uniformly distributed
* Normally distributed measurement error
* Have an initial point estimate (observed minimum)

### Set parameters

```{r}
set.seed(22)
alpha = 0.05
K = 20000 # upper bound for dates we can get fossils in
```

### Import data

```{r}
library(readxl)
# Import mammoth data from fossildata.xlsx
fossil_dataframe = read_excel(
  path='../data/fossildata.xlsx', 
  sheet="MammothPrimEBer", 
  range="M3:N36", 
  col_names=c("age", "sd"), 
  col_types=c('numeric', 'numeric')
)
fossil_dataframe = fossil_dataframe[fossil_dataframe$age<K,]


dating_error.sd = mean(fossil_dataframe$sd)
```

```{r}
source("garthwaite-robbins-munro-functions.R")
```

```{r}
load("../data/synthetic-data.RData")
dates = datasets[1, ]$W[[1]]
n = length(dates)
theta.hat.y = min(dates)
```

```{r}
res = estimate_CI.rm(W=dates,
                     K=K,
                     alpha=0.05,
                     max_iter=1000,
                     eps.mean=0,
                     eps.sigma=0*mean(fossil_dataframe$sd),
                     return_iters=T)
c(res$CI.lower, res$CI.upper, res$point)

plot(na.omit(res$upper.iters), pch=4, type="l", xlab="i", col='red', ylab=NA, main="CI Convergence",
     xlim=c(0, max(length(res$lower.iters), length(res$upper.iters))),
     ylim=c(min(res$lower.iters, res$upper.iters), max(res$lower.iters, res$upper.iters)))

lines(res$lower.iters, pch=4, col='blue')
lines(res$point.iters, pch=4, col='purple')
abline(h=theta.hat.y, lty=2, col="black")

legend("right", legend=c("U_i", "L_i", "m"), col=c("red", "blue", "black"), lty=c(1,1,1))
```

```{r}
res = estimate_CI.rm(W=dates,
                     K=K,
                     alpha=0.05,
                     max_iter=1000,
                     eps.mean=0,
                     eps.sigma=mean(fossil_dataframe$sd),
                     return_iters=T)
c(res$CI.lower, res$CI.upper, res$point)

plot(na.omit(res$upper.iters), pch=4, type="l", xlab="i", col='red', ylab=NA, main="CI Convergence",
     xlim=c(0, max(length(res$lower.iters), length(res$upper.iters))),
     ylim=c(min(res$lower.iters), max(res$upper.iters)))

lines(res$lower.iters, pch=4, col='blue')
lines(res$point.iters, pch=4, col='purple')
abline(h=theta.hat.y, lty=2, col="black")

legend("right", legend=c("U_i", "L_i", "m"), col=c("red", "blue", "black"), lty=c(1,1,1))
```


